version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: react-scripts
    versions:
    - 4.0.3
  - dependency-name: react-bootstrap
    versions:
    - 1.5.2
  - dependency-name: "@testing-library/jest-dom"
    versions:
    - 5.11.10
